const data = [
  {
    category: 'Watch',
    itemName: 'A-Watch',
    price: '$39.99',
    discount: '5%',
    imageUrl: 'https://source.unsplash.com/4R_WEmhx8og',
  },
  {
    category: 'Watch',
    itemName: 'B-Watch',
    price: '$59.99',
    discount: '5%',
    imageUrl: 'https://source.unsplash.com/xfNeB1stZ_0',
  },
  {
    category: 'Watch',
    itemName: 'C-Watch',
    price: '$49.99',
    discount: '5%',
    imageUrl: 'https://source.unsplash.com/71_GA1KBf_8',
  },
  {
    category: 'Watch',
    itemName: 'D-Watch',
    price: '$109.99',
    discount: '10%',
    imageUrl: 'https://source.unsplash.com/Ae3OHpJfngc',
  },
  {
    category: 'Dress',
    itemName: 'A-Dress',
    price: '$205.99',
    discount: '15%',
    imageUrl: 'https://source.unsplash.com/tyfqOL1FAQc',
  },
  {
    category: 'Dress',
    itemName: 'B-Dress',
    price: '$199.99',
    discount: '15%',
    imageUrl: 'https://source.unsplash.com/_vmoFgZc8c0',
  },
  {
    category: 'Dress',
    itemName: 'C-Dress',
    price: '$280.99',
    discount: '20%',
    imageUrl: 'https://source.unsplash.com/4mLKBKMPoHo',
  },
  {
    category: 'Dress',
    itemName: 'D-Dress',
    price: '$150.99',
    discount: '15%',
    imageUrl: 'https://source.unsplash.com/zwFcGxoKJ1c',
  },
  {
    category: 'Swimsuit',
    itemName: 'A-Swinsuit',
    price: '$99.99',
    discount: '5%',
    imageUrl: 'https://source.unsplash.com/f4mLA8nDbRg',
  },
  {
    category: 'Swimsuit',
    itemName: 'B-Swinsuit',
    price: '$99.99',
    discount: '5%',
    imageUrl: 'https://source.unsplash.com/yWSBfNFMuQg',
  },
  {
    category: 'Swimsuit',
    itemName: 'C-Swinsuit',
    price: '$110.99',
    discount: '8%',
    imageUrl: 'https://source.unsplash.com/vBEaToq8tcg',
  },
  {
    category: 'Swimsuit',
    itemName: 'D-Swinsuit',
    price: '$89.99',
    discount: '5%',
    imageUrl: 'https://source.unsplash.com/Pvfub0cevTw',
  },
];

export default data;
